# -*- coding: utf-8 -*-
"""CEMEAM Conversão Minuta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1Cwj3RAZ5m2Ergg6Ryzv2GDkm0iQtAw
"""

# Instalar bibliotecas necessárias (se ainda não estiverem instaladas)
!pip install pandas openpyxl python-docx -qq

import pandas as pd
from docx import Document

# Função auxiliar para formatar cada valor como string,
# especialmente as datas (Timestamp).
def formatar_valor(valor):
    if pd.isnull(valor):
        return ''
    if isinstance(valor, pd.Timestamp):
        return valor.strftime('%d/%m/%Y')
    return str(valor)

# 1) Carrega os arquivos Excel
# Se estiver no Google Colab, certifique-se de que os arquivos foram carregados
# para o ambiente, ou utilize o caminho completo do Google Drive.
df_modelo = pd.read_excel('MODELO.xlsx')
df_cemeam = pd.read_excel('CEMEAM_extra.xlsx')

# 2) Cria o documento Word
document = Document()

# Utiliza a linha de modelo (primeira linha) do arquivo modelo.xlsx
modelo = df_modelo.iloc[0].copy()

# 3) Itera sobre cada linha do CEMEAM.xlsx
for idx, row in df_cemeam.iterrows():
    # Cria uma cópia da linha-modelo
    linha_nova = modelo.copy()

    # Preenche as colunas conforme a combinação solicitada:
    # B1.1  = SOLICITADO NOME
    # B1.3  = SOLICITADO MAT-CFPP
    # B1.5  = HORAS PAGAR
    # B1.7  = TURNO ACRESCIMO
    # B1.9  = DATA INI.
    # B1.11 = DATA FIM
    linha_nova['B1.1']  = formatar_valor(row['SOLICITADO NOME'])
    linha_nova['B1.3']  = formatar_valor(row['SOLICITADO MAT-CFPP'])
    linha_nova['B1.5']  = formatar_valor(row['HORAS PAGAR'])
    linha_nova['B1.7']  = formatar_valor(row['TURNO ACRESCIMO'])
    linha_nova['B1.9']  = formatar_valor(row['DATA INI.'])
    linha_nova['B1.11'] = formatar_valor(row['DATA FIM'])

    # Junta os valores de cada célula sem espaços entre eles
    paragrafo = ''.join(str(x) for x in linha_nova.values)

    # Adiciona o parágrafo ao documento
    document.add_paragraph(paragrafo)

# 4) Salva o arquivo Word final
document.save('saida.docx')

print("Arquivo 'saida.docx' gerado com sucesso!")