# -*- coding: utf-8 -*-
"""Criação de Minuta RC REG Ver.1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cbJosNGhguXe_B3TJOAtOhrCemqzFfxB
"""

# Instalar as bibliotecas necessárias
!pip install --quiet python-docx openpyxl pyexcel-xls

import pandas as pd
from docx import Document

# Função auxiliar para formatar cada valor como string, especialmente as datas (Timestamp)
def formatar_valor(valor):
    if pd.isnull(valor):
        return ''
    if isinstance(valor, pd.Timestamp):
        return valor.strftime('%d/%m/%Y')
    return str(valor)

# 1) Carrega os arquivos Excel
df_modelo = pd.read_excel('/content/MODELO.xlsx')
df_cemeam = pd.read_excel('/content/RC 19.03.25 ANA CLAUDIA.xlsx')

# 2) Cria o documento Word
document = Document()

# Utiliza a linha de modelo (primeira linha) do arquivo MODELO.xlsx
modelo = df_modelo.iloc[0].copy()

# 3) Verifica se a coluna "MUNICIPIO LOCAL" existe
if "MUNICIPIO LOCAL" not in df_cemeam.columns:
    raise ValueError("A coluna 'MUNICIPIO LOCAL' não está presente no arquivo")

# 4) Agrupa os dados pelo MUNICIPIO LOCAL
municipios = df_cemeam["MUNICIPIO LOCAL"].unique()

# Itera sobre cada MUNICIPIO LOCAL e adiciona ao documento
for municipio in municipios:
    # Adiciona o nome do município como um título antes dos dados relacionados a ele
    document.add_paragraph(f"MUNICIPIO: {municipio}", style="Heading 2")

    # Filtra apenas as linhas do município atual
    df_municipio = df_cemeam[df_cemeam["MUNICIPIO LOCAL"] == municipio]

    # Itera sobre cada linha do município e adiciona ao documento
    for _, row in df_municipio.iterrows():
        linha_nova = modelo.copy()

        # Preenche as colunas conforme a combinação solicitada
        linha_nova['B1.1']  = formatar_valor(row['SOLICITADO NOME'])
        linha_nova['B1.3']  = formatar_valor(row['SOLICITADO MAT-CFPP'])
        linha_nova['B1.5']  = formatar_valor(row['HORAS PAGAR'])
        linha_nova['B1.7']  = formatar_valor(row[' COMPONENTE 1'])
        linha_nova['B1.9']  = formatar_valor(row['TURNO ACRESCIMO'])
        linha_nova['B1.11']  = formatar_valor(row['DATA INI.'])
        linha_nova['B1.13'] = formatar_valor(row['DATA FIM'])

        # Junta os valores da linha sem espaços entre eles
        paragrafo = ''.join(str(x) for x in linha_nova.values)

        # Adiciona o parágrafo ao documento
        document.add_paragraph(paragrafo)

# 5) Salva o arquivo Word final
document.save('RC 19.03.25.docx')

print("Arquivo 'RC 19.03.25.docx' gerado com sucesso!")